title:              Stackcodeid
email:              sarimie.isii2.com
description:        Blog Teknisi Telepon Selular
author:             Stackcodeid
baseurl:            "/stackcodeid.github.io"
url:                "https://stackcodeid.github.io"

# Social Profiles
twitter_username:   22_jgsayangayah
github_username:    stackcodeid
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           3
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
